/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geneticalgorithm;

import java.util.Arrays;
import java.util.Stack;

/**
 *
 * @author hasalp
 */
public class CreatePath extends javax.swing.JFrame {

    private int[][] choosed = new int[4][5];
    private int count = 0;
    
    public CreatePath() {
        for(int row[]: choosed){
            Arrays.fill(row, 0);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        point0x0 = new javax.swing.JButton();
        point1x0 = new javax.swing.JButton();
        point1x1 = new javax.swing.JButton();
        point0x1 = new javax.swing.JButton();
        point1x2 = new javax.swing.JButton();
        point0x2 = new javax.swing.JButton();
        point1x3 = new javax.swing.JButton();
        point0x3 = new javax.swing.JButton();
        point1x4 = new javax.swing.JButton();
        point0x4 = new javax.swing.JButton();
        point2x0 = new javax.swing.JButton();
        point2x1 = new javax.swing.JButton();
        point2x2 = new javax.swing.JButton();
        point2x3 = new javax.swing.JButton();
        point2x4 = new javax.swing.JButton();
        point3x0 = new javax.swing.JButton();
        point3x1 = new javax.swing.JButton();
        point3x2 = new javax.swing.JButton();
        point3x3 = new javax.swing.JButton();
        point3x4 = new javax.swing.JButton();
        createPath = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        point0x0.setText("-");
        point0x0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point0x0ActionPerformed(evt);
            }
        });

        point1x0.setText("-");
        point1x0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point1x0ActionPerformed(evt);
            }
        });

        point1x1.setText("-");
        point1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point1x1ActionPerformed(evt);
            }
        });

        point0x1.setText("-");
        point0x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point0x1ActionPerformed(evt);
            }
        });

        point1x2.setText("-");
        point1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point1x2ActionPerformed(evt);
            }
        });

        point0x2.setText("-");
        point0x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point0x2ActionPerformed(evt);
            }
        });

        point1x3.setText("-");
        point1x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point1x3ActionPerformed(evt);
            }
        });

        point0x3.setText("-");
        point0x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point0x3ActionPerformed(evt);
            }
        });

        point1x4.setText("-");
        point1x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point1x4ActionPerformed(evt);
            }
        });

        point0x4.setText("-");
        point0x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point0x4ActionPerformed(evt);
            }
        });

        point2x0.setText("-");
        point2x0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point2x0ActionPerformed(evt);
            }
        });

        point2x1.setText("-");
        point2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point2x1ActionPerformed(evt);
            }
        });

        point2x2.setText("-");
        point2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point2x2ActionPerformed(evt);
            }
        });

        point2x3.setText("-");
        point2x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point2x3ActionPerformed(evt);
            }
        });

        point2x4.setText("-");
        point2x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point2x4ActionPerformed(evt);
            }
        });

        point3x0.setText("-");
        point3x0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point3x0ActionPerformed(evt);
            }
        });

        point3x1.setText("-");
        point3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point3x1ActionPerformed(evt);
            }
        });

        point3x2.setText("-");
        point3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point3x2ActionPerformed(evt);
            }
        });

        point3x3.setText("-");
        point3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point3x3ActionPerformed(evt);
            }
        });

        point3x4.setText("-");
        point3x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point3x4ActionPerformed(evt);
            }
        });

        createPath.setText("Create Path");
        createPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPathActionPerformed(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(createPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(point0x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point1x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(point0x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(point0x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(point0x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(point0x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(point2x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(point3x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(point3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(point0x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(point1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(point0x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(point1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(point0x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(point1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(point0x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(point1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(point0x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(point1x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(point2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(point2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(point2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point2x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(point3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(point3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(point3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(point3x0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createPath, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void point0x0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point0x0ActionPerformed
        if(choosed[0][0]==0){
            choosed[0][0]=1;
            point0x0.setText("X");
        }else{
            choosed[0][0]=0;
            point0x0.setText("-");
        }
    }//GEN-LAST:event_point0x0ActionPerformed

    private void point0x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point0x1ActionPerformed
        if(choosed[0][1]==0){
            choosed[0][1]=1;
            point0x1.setText("X");
        }else{
            choosed[0][1]=0;
            point0x1.setText("-");
        }
    }//GEN-LAST:event_point0x1ActionPerformed

    private void point0x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point0x2ActionPerformed
        if(choosed[0][2]==0){
            choosed[0][2]=1;
            point0x2.setText("X");
        }else{
            choosed[0][2]=0;
            point0x2.setText("-");
        }
    }//GEN-LAST:event_point0x2ActionPerformed

    private void point0x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point0x3ActionPerformed
        if(choosed[0][3]==0){
            choosed[0][3]=1;
            point0x3.setText("X");
        }else{
            choosed[0][3]=0;
            point0x3.setText("-");
        }
    }//GEN-LAST:event_point0x3ActionPerformed

    private void point1x0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point1x0ActionPerformed
        if(choosed[1][0]==0){
            choosed[1][0]=1;
            point1x0.setText("X");
        }else{
            choosed[1][0]=0;
            point1x0.setText("-");
        }
    }//GEN-LAST:event_point1x0ActionPerformed

    private void point1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point1x1ActionPerformed
        if(choosed[1][1]==0){
            choosed[1][1]=1;
            point1x1.setText("X");
        }else{
            choosed[1][1]=0;
            point1x1.setText("-");
        }
    }//GEN-LAST:event_point1x1ActionPerformed

    private void point1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point1x2ActionPerformed
        if(choosed[1][2]==0){
            choosed[1][2]=1;
            point1x2.setText("X");
        }else{
            choosed[1][2]=0;
            point1x2.setText("-");
        }
    }//GEN-LAST:event_point1x2ActionPerformed

    private void point1x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point1x3ActionPerformed
        if(choosed[1][3]==0){
            choosed[1][3]=1;
            point1x3.setText("X");
        }else{
            choosed[1][3]=0;
            point1x3.setText("-");
        }
    }//GEN-LAST:event_point1x3ActionPerformed

    private void point1x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point1x4ActionPerformed
        if(choosed[1][4]==0){
            choosed[1][4]=1;
            point1x4.setText("X");
        }else{
            choosed[1][4]=0;
            point1x4.setText("-");
        }
    }//GEN-LAST:event_point1x4ActionPerformed

    private void point2x0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point2x0ActionPerformed
        if(choosed[2][0]==0){
            choosed[2][0]=1;
            point2x0.setText("X");
        }else{
            choosed[2][0]=0;
            point2x0.setText("-");
        }
    }//GEN-LAST:event_point2x0ActionPerformed

    private void point2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point2x1ActionPerformed
        if(choosed[2][1]==0){
            choosed[2][1]=1;
            point2x1.setText("X");
        }else{
            choosed[2][1]=0;
            point2x1.setText("-");
        }
    }//GEN-LAST:event_point2x1ActionPerformed

    private void point2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point2x2ActionPerformed
        if(choosed[2][2]==0){
            choosed[2][2]=1;
            point2x2.setText("X");
        }else{
            choosed[2][2]=0;
            point2x2.setText("-");
        }
    }//GEN-LAST:event_point2x2ActionPerformed

    private void point2x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point2x3ActionPerformed
        if(choosed[2][3]==0){
            choosed[2][3]=1;
            point2x3.setText("X");
        }else{
            choosed[2][3]=0;
            point2x3.setText("-");
        }
    }//GEN-LAST:event_point2x3ActionPerformed

    private void point2x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point2x4ActionPerformed
        if(choosed[2][4]==0){
            choosed[2][4]=1;
            point2x4.setText("X");
        }else{
            choosed[2][4]=0;
            point2x4.setText("-");
        }
    }//GEN-LAST:event_point2x4ActionPerformed

    private void point3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point3x1ActionPerformed
        if(choosed[3][1]==0){
            choosed[3][1]=1;
            point3x1.setText("X");
        }else{
            choosed[3][1]=0;
            point3x1.setText("-");
        }
    }//GEN-LAST:event_point3x1ActionPerformed

    private void point3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point3x2ActionPerformed
        if(choosed[3][2]==0){
            choosed[3][2]=1;
            point3x2.setText("X");
        }else{
            choosed[3][2]=0;
            point3x2.setText("-");
        }
    }//GEN-LAST:event_point3x2ActionPerformed

    private void point3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point3x3ActionPerformed
        if(choosed[3][3]==0){
            choosed[3][3]=1;
            point3x3.setText("X");
        }else{
            choosed[3][3]=0;
            point3x3.setText("-");
        }
    }//GEN-LAST:event_point3x3ActionPerformed

    private void point3x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point3x4ActionPerformed
        if(choosed[3][4]==0){
            choosed[3][4]=1;
            point3x4.setText("X");
        }else{
            choosed[3][4]=0;
            point3x4.setText("-");
        }
    }//GEN-LAST:event_point3x4ActionPerformed

    private void createPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPathActionPerformed
        result.setText("");
        int stopper=0;
        Stack<String> crossOver = new Stack<>();
        Stack<Double> Measurements = new Stack<>();
        Stack<Double> finalMeasurements = new Stack<>();
        //prepare selected permutations of selected points.
        Chromosome path = new Chromosome(choosed);
        //set first population
        Population population = new Population(path.prepareChromosome(path.CheckPoints()));
        //get current population
        while(stopper<Math.pow(path.genCount,5)){
            CreatePath.result.append("------Generation "+stopper+"-----\n");
            Stack<String> currentPopulation = population.getPopulation();
            Stack<String> crossPopulation = new Stack<>();
            Stack<String> mutatedPopulation = new Stack<>();
            crossPopulation = (Stack<String>) currentPopulation.clone();
            //get measurement of current population
            Measurements = population.getMeasurements(currentPopulation);

            //crossOver
            while(crossPopulation.size()>1){
                String selectedChromosome = population.selectFromWheel(crossPopulation);
                crossPopulation.remove(selectedChromosome);
                crossOver.push(population.crossover(selectedChromosome, crossPopulation.pop()));
            }

            printPopulation(crossOver,"Crossover");
            //mutation
            while(crossOver.size()>0){
                mutatedPopulation.push(population.mutation(crossOver.pop()));
            }

            printPopulation(mutatedPopulation,"Mutation");

            finalMeasurements = population.getMeasurements(mutatedPopulation);


            for(int i=0; i<currentPopulation.size(); i++){
                count = 0;
                int size = mutatedPopulation.size();
                while(count<size-1){
                    if(finalMeasurements.get(count)<Measurements.get(i)){
                        currentPopulation.set(i, mutatedPopulation.get(count));
                        mutatedPopulation.remove(count);
                        finalMeasurements.remove(count);
                    }
                    count++;
                }
            }

            population.setPopulation(currentPopulation);
            stopper++;
        }
    }//GEN-LAST:event_createPathActionPerformed

    private void printPopulation(Stack<String> population, String title){
        count = 0;
        CreatePath.result.append("------"+title+"-----\n");
        while(count<population.size()){
            CreatePath.result.append(population.get(count)+"\n");
            count++;
        }
    }
    
    private void point3x0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point3x0ActionPerformed
        if(choosed[3][0]==0){
            choosed[3][0]=1;
            point3x0.setText("X");
        }else{
            choosed[3][0]=0;
            point3x0.setText("-");
        }
    }//GEN-LAST:event_point3x0ActionPerformed

    private void point0x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point0x4ActionPerformed
        if(choosed[0][4]==0){
            choosed[0][4]=1;
            point0x4.setText("X");
        }else{
            choosed[0][4]=0;
            point0x4.setText("-");
        }
    }//GEN-LAST:event_point0x4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePath().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPath;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton point0x0;
    private javax.swing.JButton point0x1;
    private javax.swing.JButton point0x2;
    private javax.swing.JButton point0x3;
    private javax.swing.JButton point0x4;
    private javax.swing.JButton point1x0;
    private javax.swing.JButton point1x1;
    private javax.swing.JButton point1x2;
    private javax.swing.JButton point1x3;
    private javax.swing.JButton point1x4;
    private javax.swing.JButton point2x0;
    private javax.swing.JButton point2x1;
    private javax.swing.JButton point2x2;
    private javax.swing.JButton point2x3;
    private javax.swing.JButton point2x4;
    private javax.swing.JButton point3x0;
    private javax.swing.JButton point3x1;
    private javax.swing.JButton point3x2;
    private javax.swing.JButton point3x3;
    private javax.swing.JButton point3x4;
    public static javax.swing.JTextArea result;
    // End of variables declaration//GEN-END:variables
}
